# Generated by Django 3.0.5 on 2020-04-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200409_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Hat'),
        ),
    ]
